// Project/App: OTTO
// File Purpose: Canonical workflow MCP tool metadata shared across package boundaries.

export type WorkflowToolWritePolicy = "read" | "write";

export interface WorkflowToolContractMetadata {
	canonicalName: string;
	aliases: readonly string[];
	schemaId: string;
	executorId: string;
	writePolicy: WorkflowToolWritePolicy;
	auditEvent: string;
}

export const WORKFLOW_TOOL_CONTRACTS = [
	{
		canonicalName: "otto_decision_save",
		aliases: ["otto_save_decision"],
		schemaId: "workflow.decision.save",
		executorId: "executeDecisionSave",
		writePolicy: "write",
		auditEvent: "workflow.decision.save",
	},
	{
		canonicalName: "otto_requirement_update",
		aliases: ["otto_update_requirement"],
		schemaId: "workflow.requirement.update",
		executorId: "executeRequirementUpdate",
		writePolicy: "write",
		auditEvent: "workflow.requirement.update",
	},
	{
		canonicalName: "otto_requirement_save",
		aliases: ["otto_save_requirement"],
		schemaId: "workflow.requirement.save",
		executorId: "executeRequirementSave",
		writePolicy: "write",
		auditEvent: "workflow.requirement.save",
	},
	{
		canonicalName: "otto_milestone_generate_id",
		aliases: ["otto_generate_milestone_id"],
		schemaId: "workflow.milestone.generate_id",
		executorId: "executeMilestoneGenerateId",
		writePolicy: "read",
		auditEvent: "workflow.milestone.generate_id",
	},
	{
		canonicalName: "otto_plan_milestone",
		aliases: [],
		schemaId: "workflow.milestone.plan",
		executorId: "executePlanMilestone",
		writePolicy: "write",
		auditEvent: "workflow.milestone.plan",
	},
	{
		canonicalName: "otto_plan_slice",
		aliases: [],
		schemaId: "workflow.slice.plan",
		executorId: "executePlanSlice",
		writePolicy: "write",
		auditEvent: "workflow.slice.plan",
	},
	{
		canonicalName: "otto_plan_task",
		aliases: ["otto_task_plan"],
		schemaId: "workflow.task.plan",
		executorId: "executePlanTask",
		writePolicy: "write",
		auditEvent: "workflow.task.plan",
	},
	{
		canonicalName: "otto_replan_slice",
		aliases: ["otto_slice_replan"],
		schemaId: "workflow.slice.replan",
		executorId: "executeReplanSlice",
		writePolicy: "write",
		auditEvent: "workflow.slice.replan",
	},
	{
		canonicalName: "otto_slice_complete",
		aliases: ["otto_complete_slice"],
		schemaId: "workflow.slice.complete",
		executorId: "executeSliceComplete",
		writePolicy: "write",
		auditEvent: "workflow.slice.complete",
	},
	{
		canonicalName: "otto_skip_slice",
		aliases: [],
		schemaId: "workflow.slice.skip",
		executorId: "executeSkipSlice",
		writePolicy: "write",
		auditEvent: "workflow.slice.skip",
	},
	{
		canonicalName: "otto_complete_milestone",
		aliases: ["otto_milestone_complete"],
		schemaId: "workflow.milestone.complete",
		executorId: "executeCompleteMilestone",
		writePolicy: "write",
		auditEvent: "workflow.milestone.complete",
	},
	{
		canonicalName: "otto_validate_milestone",
		aliases: ["otto_milestone_validate"],
		schemaId: "workflow.milestone.validate",
		executorId: "executeValidateMilestone",
		writePolicy: "write",
		auditEvent: "workflow.milestone.validate",
	},
	{
		canonicalName: "otto_reassess_roadmap",
		aliases: ["otto_roadmap_reassess"],
		schemaId: "workflow.roadmap.reassess",
		executorId: "executeReassessRoadmap",
		writePolicy: "write",
		auditEvent: "workflow.roadmap.reassess",
	},
	{
		canonicalName: "otto_save_gate_result",
		aliases: [],
		schemaId: "workflow.gate.save_result",
		executorId: "executeSaveGateResult",
		writePolicy: "write",
		auditEvent: "workflow.gate.save_result",
	},
	{
		canonicalName: "otto_summary_save",
		aliases: [],
		schemaId: "workflow.summary.save",
		executorId: "executeSummarySave",
		writePolicy: "write",
		auditEvent: "workflow.summary.save",
	},
	{
		canonicalName: "otto_task_complete",
		aliases: ["otto_complete_task"],
		schemaId: "workflow.task.complete",
		executorId: "executeTaskComplete",
		writePolicy: "write",
		auditEvent: "workflow.task.complete",
	},
	{
		canonicalName: "otto_task_reopen",
		aliases: ["otto_reopen_task"],
		schemaId: "workflow.task.reopen",
		executorId: "executeTaskReopen",
		writePolicy: "write",
		auditEvent: "workflow.task.reopen",
	},
	{
		canonicalName: "otto_slice_reopen",
		aliases: ["otto_reopen_slice"],
		schemaId: "workflow.slice.reopen",
		executorId: "executeSliceReopen",
		writePolicy: "write",
		auditEvent: "workflow.slice.reopen",
	},
	{
		canonicalName: "otto_milestone_reopen",
		aliases: ["otto_reopen_milestone"],
		schemaId: "workflow.milestone.reopen",
		executorId: "executeMilestoneReopen",
		writePolicy: "write",
		auditEvent: "workflow.milestone.reopen",
	},
	{
		canonicalName: "otto_milestone_status",
		aliases: [],
		schemaId: "workflow.milestone.status",
		executorId: "executeMilestoneStatus",
		writePolicy: "read",
		auditEvent: "workflow.milestone.status",
	},
	{
		canonicalName: "otto_journal_query",
		aliases: [],
		schemaId: "workflow.journal.query",
		executorId: "executeJournalQuery",
		writePolicy: "read",
		auditEvent: "workflow.journal.query",
	},
	{
		canonicalName: "otto_exec",
		aliases: [],
		schemaId: "workflow.exec.run",
		executorId: "executeWorkflowExec",
		writePolicy: "write",
		auditEvent: "workflow.exec.run",
	},
	{
		canonicalName: "otto_exec_search",
		aliases: [],
		schemaId: "workflow.exec.search",
		executorId: "executeWorkflowExecSearch",
		writePolicy: "read",
		auditEvent: "workflow.exec.search",
	},
	{
		canonicalName: "otto_resume",
		aliases: [],
		schemaId: "workflow.resume",
		executorId: "executeWorkflowResume",
		writePolicy: "read",
		auditEvent: "workflow.resume",
	},
	{
		canonicalName: "otto_capture_thought",
		aliases: [],
		schemaId: "workflow.memory.capture_thought",
		executorId: "executeCaptureThought",
		writePolicy: "write",
		auditEvent: "workflow.memory.capture_thought",
	},
	{
		canonicalName: "otto_memory_query",
		aliases: [],
		schemaId: "workflow.memory.query",
		executorId: "executeMemoryQuery",
		writePolicy: "read",
		auditEvent: "workflow.memory.query",
	},
	{
		canonicalName: "otto_memory_graph",
		aliases: [],
		schemaId: "workflow.memory.graph",
		executorId: "executeMemoryGraph",
		writePolicy: "read",
		auditEvent: "workflow.memory.graph",
	},
] as const satisfies readonly WorkflowToolContractMetadata[];

export const WORKFLOW_TOOL_NAMES = WORKFLOW_TOOL_CONTRACTS.flatMap((tool) => [
	tool.canonicalName,
	...tool.aliases,
]) as readonly string[];
