/**
 * Prompt-engineer history storage.
 *
 * Saves each polished prompt to ~/.loop24/prompts/<YYYY-MM-DD>-<slug>.md
 * atomically (tmp + rename). Collision-safe: same-day same-slug appends a
 * UTC time suffix.
 *
 * Default baseDir: ~/.loop24/prompts. Tests inject a temp dir via the
 * baseDir option.
 */

import { writeFile, mkdir, rename } from "node:fs/promises";
import { existsSync } from "node:fs";
import { join } from "node:path";
import { homedir } from "node:os";

export interface SavePromptHistoryOptions {
  description: string;
  polished: string;
  modelId: string;
  baseDir?: string;
}

const FALLBACK_SLUG = "prompt";
const MAX_SLUG_LEN = 50;

export function slugify(text: string): string {
  const normalized = text
    .normalize("NFKD")
    .replace(/[̀-ͯ]/g, "")    // strip combining diacritics
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .replace(/-{2,}/g, "-");

  if (normalized.length === 0) return FALLBACK_SLUG;
  if (normalized.length <= MAX_SLUG_LEN) return normalized;

  const cut = normalized.slice(0, MAX_SLUG_LEN);
  const lastHyphen = cut.lastIndexOf("-");
  return (lastHyphen > 20 ? cut.slice(0, lastHyphen) : cut).replace(/-+$/, "");
}

function defaultBaseDir(): string {
  return join(homedir(), ".loop24", "prompts");
}

function todayUtcDate(): string {
  return new Date().toISOString().slice(0, 10);
}

function utcTimeSuffix(): string {
  return new Date().toISOString().slice(11, 19).replace(/:/g, "");
}

function buildMarkdown(
  description: string,
  polished: string,
  modelId: string,
  generatedAt: string,
): string {
  return [
    `# Polished prompt — ${generatedAt}`,
    "",
    "## Original request",
    "",
    "```",
    description,
    "```",
    "",
    "## Polished prompt",
    "",
    polished,
    "",
    "---",
    `Model: \`${modelId}\``,
    `Generated by \`/loop24 prompt-engineer\``,
    "",
  ].join("\n");
}

export async function savePromptHistory(opts: SavePromptHistoryOptions): Promise<string> {
  const baseDir = opts.baseDir ?? defaultBaseDir();
  await mkdir(baseDir, { recursive: true });

  const date = todayUtcDate();
  const slug = slugify(opts.description);
  let path = join(baseDir, `${date}-${slug}.md`);
  if (existsSync(path)) {
    const suffix = utcTimeSuffix();
    path = join(baseDir, `${date}-${slug}-${suffix}.md`);
    let i = 0;
    while (existsSync(path)) {
      path = join(baseDir, `${date}-${slug}-${suffix}-${++i}.md`);
    }
  }

  const generatedAt = new Date().toISOString();
  const body = buildMarkdown(opts.description, opts.polished, opts.modelId, generatedAt);

  const tmpPath = `${path}.tmp`;
  await writeFile(tmpPath, body, { mode: 0o600 });
  await rename(tmpPath, path);
  return path;
}
