import { execSync, spawn } from 'node:child_process'
import { existsSync, mkdirSync, mkdtempSync, readFileSync, writeFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { agentDir as defaultAgentDir } from './app-paths.js'
import { initResources } from './resource-loader.js'
import { compareSemver, fetchLatestVersionFromRegistry, resolveInstallCommand } from './update-check.js'

const NPM_PACKAGE = '@cmetech/otto'

interface RunUpdateOptions {
  agentDir?: string
  skillsDir?: string
}

interface UpdateStatus {
  startedAt: string
  completedAt?: string
  fromVersion: string
  toVersion: string
  exitCode?: number
}

function getStatusPath(agentDir: string): string {
  return join(agentDir, 'update-status.json')
}

function maybeShowPriorStatus(agentDir: string): void {
  const statusPath = getStatusPath(agentDir)
  if (!existsSync(statusPath)) return
  try {
    const status = JSON.parse(readFileSync(statusPath, 'utf-8')) as UpdateStatus
    if (status.completedAt) {
      const dim = '\x1b[2m'
      const reset = '\x1b[0m'
      const outcome = status.exitCode === 0 ? '✓ success' : `✗ exit ${status.exitCode}`
      process.stdout.write(
        `${dim}Last update: v${status.fromVersion} → v${status.toVersion} at ${status.completedAt} (${outcome})${reset}\n`,
      )
    }
  } catch {
    // Ignore parse errors — file may be partial or corrupt.
  }
}

/**
 * Build the PowerShell bootstrap that runs the install in a detached, visible
 * console window. Exported for tests. The script:
 *   1. Writes an initial status file at `statusPath`.
 *   2. Waits up to 30s for the parent otto.exe (parentPid) to exit so its
 *      DLL handles release.
 *   3. Runs the install command (`npm install -g …` or `bun add -g …`).
 *   4. Sweeps any orphan `.otto-*` staging dirs npm left behind.
 *   5. Updates the status file with completion details.
 *   6. Prints a clear "Done" message and waits for a keypress.
 */
export function buildWindowsBootstrapScript(args: {
  parentPid: number
  installCmd: string
  statusPath: string
  current: string
  latest: string
  startedAt: string
}): string {
  // PowerShell single-quoted strings are literal — backslashes and $ are not
  // interpreted. Path values flow straight through.
  const psQuote = (value: string): string => `'${value.replace(/'/g, "''")}'`
  const status = psQuote(args.statusPath)
  const current = psQuote(args.current)
  const latest = psQuote(args.latest)
  const startedAt = psQuote(args.startedAt)
  const installCmd = args.installCmd // run as-is — must be a valid PowerShell command line

  return `# OTTO update bootstrap — auto-generated by otto update on Windows
$ErrorActionPreference = 'Continue'
$Host.UI.RawUI.WindowTitle = 'OTTO Updater'

Write-Host 'OTTO Updater — please do not close this window' -ForegroundColor Cyan
Write-Host '─────────────────────────────────────────────────'
Write-Host ''

# Write initial status
$statusPath = ${status}
$statusDir = Split-Path -Parent $statusPath
if ($statusDir -and -not (Test-Path $statusDir)) {
  New-Item -ItemType Directory -Path $statusDir -Force | Out-Null
}
@{
  startedAt   = ${startedAt}
  fromVersion = ${current}
  toVersion   = ${latest}
} | ConvertTo-Json | Set-Content -Path $statusPath -Encoding UTF8

# Wait for parent otto.exe (pid ${args.parentPid}) to exit, max 30s
Write-Host -NoNewline 'Waiting for OTTO to exit...'
$deadline = (Get-Date).AddSeconds(30)
while ((Get-Process -Id ${args.parentPid} -ErrorAction SilentlyContinue) -and ((Get-Date) -lt $deadline)) {
  Start-Sleep -Milliseconds 300
}
if (Get-Process -Id ${args.parentPid} -ErrorAction SilentlyContinue) {
  Write-Host ' timeout!' -ForegroundColor Yellow
  Write-Host 'OTTO did not exit in 30s. To finish manually, run:' -ForegroundColor Yellow
  Write-Host ('  ' + ${psQuote(installCmd)})
  Write-Host ''
  Write-Host 'Press any key to close this window.'
  $null = $Host.UI.RawUI.ReadKey('NoEcho,IncludeKeyDown')
  exit 1
}
Write-Host ' done.'
Write-Host ''

# Run the install
Write-Host ('Running: ' + ${psQuote(installCmd)}) -ForegroundColor Cyan
Write-Host ''
${installCmd}
$exitCode = $LASTEXITCODE

# Sweep orphan .otto-* staging dirs npm couldn't clean up
$stagingRoot = Join-Path $env:APPDATA 'npm\\node_modules\\@cmetech'
if (Test-Path $stagingRoot) {
  Get-ChildItem -Path $stagingRoot -Directory -Filter '.otto-*' -ErrorAction SilentlyContinue |
    Remove-Item -Recurse -Force -ErrorAction SilentlyContinue
}

# Write final status
@{
  startedAt   = ${startedAt}
  completedAt = (Get-Date -Format 'o')
  fromVersion = ${current}
  toVersion   = ${latest}
  exitCode    = $exitCode
} | ConvertTo-Json | Set-Content -Path $statusPath -Encoding UTF8

Write-Host ''
if ($exitCode -eq 0) {
  Write-Host ('Done. OTTO v' + ${latest} + ' installed.') -ForegroundColor Green
  Write-Host 'Open any terminal and run otto to use the new version.'
} else {
  Write-Host ('Install failed with exit code ' + $exitCode) -ForegroundColor Red
  Write-Host ('Try manually: ' + ${psQuote(installCmd)})
}
Write-Host ''
Write-Host 'Press any key to close this window.'
$null = $Host.UI.RawUI.ReadKey('NoEcho,IncludeKeyDown')
exit $exitCode
`
}

function runWindowsDetachedUpdate(
  current: string,
  latest: string,
  installCmd: string,
  agentDir: string,
): never {
  const tempDir = mkdtempSync(join(tmpdir(), 'otto-update-'))
  const scriptPath = join(tempDir, 'update.ps1')
  const statusPath = getStatusPath(agentDir)
  const startedAt = new Date().toISOString()

  if (!existsSync(agentDir)) {
    mkdirSync(agentDir, { recursive: true })
  }

  const script = buildWindowsBootstrapScript({
    parentPid: process.pid,
    installCmd,
    statusPath,
    current,
    latest,
    startedAt,
  })
  writeFileSync(scriptPath, script, 'utf-8')

  const bold = '\x1b[1m'
  const dim = '\x1b[2m'
  const reset = '\x1b[0m'

  process.stdout.write(`${dim}Updating:${reset} v${current} → ${bold}v${latest}${reset}\n\n`)
  process.stdout.write(
    'Update is running in a new window — Windows cannot replace files while OTTO is open.\n',
  )
  process.stdout.write(
    `When the update window shows ${bold}"Done."${reset} run \`otto\` in any terminal to use v${latest}.\n\n`,
  )

  // `cmd.exe /c start "Title" powershell.exe -File <script>`
  // Node quotes args that contain spaces, so `start OTTO Updater` becomes
  // `start "OTTO Updater"`, which CMD's start builtin treats as the window
  // title (longstanding CMD quirk).
  const child = spawn(
    'cmd.exe',
    [
      '/c',
      'start',
      'OTTO Updater',
      'powershell.exe',
      '-NoProfile',
      '-ExecutionPolicy',
      'Bypass',
      '-File',
      scriptPath,
    ],
    { detached: true, stdio: 'ignore', windowsHide: false },
  )
  child.unref()

  // We MUST exit so the bootstrap's pid-wait loop unblocks and DLL handles
  // release. Anything after this point is unreachable.
  process.exit(0)
}

export async function runUpdate(options: RunUpdateOptions = {}): Promise<void> {
  const current = process.env.OTTO_VERSION || '0.0.0'
  const agentDir = options.agentDir ?? defaultAgentDir
  const bold = '\x1b[1m'
  const dim = '\x1b[2m'
  const green = '\x1b[32m'
  const yellow = '\x1b[33m'
  const reset = '\x1b[0m'

  maybeShowPriorStatus(agentDir)
  process.stdout.write(`${dim}Current version:${reset} v${current}\n`)
  process.stdout.write(`${dim}Checking npm registry...${reset}\n`)

  const latest = await fetchLatestVersionFromRegistry()
  if (!latest) {
    process.stderr.write(`${yellow}Failed to reach npm registry.${reset}\n`)
    process.exit(1)
  }

  process.stdout.write(`${dim}Latest version:${reset}  v${latest}\n`)

  if (compareSemver(latest, current) <= 0) {
    process.stdout.write(`${green}Already up to date.${reset}\n`)
    initResources(agentDir, options.skillsDir)
    return
  }

  const installCmd = resolveInstallCommand(`${NPM_PACKAGE}@latest`)

  // On Windows, run install in a detached, visible window. The current
  // process holds locks on duckdb.dll, sharp.dll, otto_engine.win32-x64.node,
  // and others — npm install would log EPERM warnings and leave orphan
  // .otto-* staging dirs (issue surfaced by a v1.0.7 → v1.1.0 update on
  // Windows). The bootstrap waits for this process to exit, runs npm install
  // cleanly, sweeps the orphans, and reports completion via a status file
  // that the next `otto update` invocation surfaces.
  if (process.platform === 'win32') {
    runWindowsDetachedUpdate(current, latest, installCmd, agentDir)
    // unreachable
  }

  process.stdout.write(`${dim}Updating:${reset} v${current} → ${bold}v${latest}${reset}\n`)
  try {
    execSync(installCmd, { stdio: 'inherit' })
    process.stdout.write(`\n${green}${bold}Updated to v${latest}${reset}\n`)
  } catch {
    process.stderr.write(`\n${yellow}Update failed. Try manually: ${installCmd}${reset}\n`)
    process.exit(1)
  }
}
